export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const CLEAR_STORE = 'CLEAR_STORE';

export const USER_LOGOUT_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGIN_FAIL';

export const CLEAR_ERRORS = "CLEAR_ERRORS";