export const url ="https://ghostwhite-guanaco-836757.hostingersite.com/wp-json/"

export const username = "ck_176cdf1ee0c4ccb0376ffa22baf84c096d5a155a";
export const password = "ck_176cdf1ee0c4ccb0376ffa22baf84c096d5a155a";

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const CLEAR_STORE = 'CLEAR_STORE';

export const USER_LOGOUT_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGIN_FAIL';

export const GET_All_FACTORY_REQUEST = 'All_FACTORY_REQUEST';
export const GET_All_FACTORY_SUCCESS = 'All_FACTORY_SUCCESS';
export const GET_All_FACTORY_FAIL = 'All_FACTORY_FAIL';

export const EDIT_FACTORY_REQUEST = 'EDIT_FACTORY_REQUEST';
export const EDIT_FACTORY_SUCCESS = 'EDIT_FACTORY_SUCCESS';
export const EDIT_FACTORY_FAIL = 'EDIT_FACTORY_SUCCESS';

export const ADD_FACTORY_REQUEST = 'ADD_FACTORY_REQUEST';
export const ADD_FACTORY_SUCCESS = 'ADD_FACTORY_SUCCESS';
export const ADD_FACTORY_FAIL = 'ADD_FACTORY_FAIL';

export const GET_ORDER_SYSTEM_REQUEST = 'GET_ORDER_SYSTEM_REQUEST';
export const GET_ORDER_SYSTEM_SUCCESS = 'GET_ORDER_SYSTEM_SUCCESS';
export const GET_ORDER_SYSTEM_FAIL = 'GET_ORDER_SYSTEM_FAIL';

export const CLEAR_ERRORS = "CLEAR_ERRORS";